# Generated by Django 2.0.2 on 2018-02-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='description',
            field=models.TextField(default='descricao'),
        ),
        migrations.AddField(
            model_name='movies',
            name='original',
            field=models.CharField(default='original', max_length=50),
        ),
    ]
